# frozen_string_literal: true

module TypeSpecFromSerializers
  # Public: Extracts type information from Sorbet method signatures.
  #
  # This module provides optional integration with Sorbet's runtime type system
  # and RBI files. It can extract type information from:
  # 1. Runtime signatures (T::Utils.signature_for_method)
  # 2. RBI files generated by Tapioca (in sorbet/rbi/ directory)
  #
  # The module gracefully degrades when sorbet-runtime is not present, making
  # Sorbet integration completely optional with zero configuration required.
  module SorbetTypeExtractor
    module_function

    # Public: Check if Sorbet runtime is available.
    #
    # Returns true if sorbet-runtime gem is loaded and the necessary APIs
    # are available for type extraction.
    #
    # Returns Boolean
    def available?
      !!(defined?(T::Utils) && T::Utils.respond_to?(:signature_for_method))
    end

    # Public: Check if RBI files are available for parsing.
    #
    # Returns true if sorbet/rbi/ directory exists (typical Tapioca setup).
    #
    # Returns Boolean
    def rbi_available?
      @rbi_available ||= begin
        path = if defined?(Rails) && Rails.respond_to?(:root) && Rails.root
          Rails.root.join("sorbet", "rbi")
        else
          Pathname.new("sorbet/rbi")
        end
        path.exist? && path.directory?
      rescue StandardError
        false
      end
    end

    # Public: Get the RBI directory path.
    #
    # Returns Pathname or nil
    def rbi_path
      return nil unless rbi_available?

      if defined?(Rails) && Rails.respond_to?(:root) && Rails.root
        Rails.root.join("sorbet", "rbi")
      else
        Pathname.new("sorbet/rbi")
      end
    end

    # Public: Extract type information for a method from its Sorbet signature.
    #
    # Tries multiple sources in order:
    # 1. Runtime reflection (T::Utils.signature_for_method)
    # 2. RBI files (if available)
    #
    # klass       - The Class containing the method
    # method_name - The Symbol or String name of the method
    #
    # Returns a Hash with keys:
    #   :typespec_type - Symbol or String representing the TypeSpec type
    #   :nilable       - Boolean indicating if type is optional
    #   :array         - Boolean indicating if type is an array
    # Returns nil if no signature found
    #
    # Examples
    #
    #   class MySerializer
    #     extend T::Sig
    #
    #     sig { returns(String) }
    #     def name
    #       "example"
    #     end
    #   end
    #
    #   extract_type_for(MySerializer, :name)
    #   # => { typespec_type: :string, nilable: false, array: false }
    #
    def extract_type_for(klass, method_name)
      # Try runtime reflection first (fastest)
      if available?
        result = SorbetTypeExtractor.send(:extract_from_runtime, klass, method_name)
        return result if result
      end

      # Fall back to RBI files (works for external gems, models, services, etc.)
      if rbi_available?
        result = SorbetTypeExtractor.send(:extract_from_rbi, klass, method_name)
        return result if result
      end

      nil
    end

    class << self
      private

    # Internal: Extract type from runtime reflection.
    def extract_from_runtime(klass, method_name)
      method = klass.instance_method(method_name.to_sym)
      extract_from_method(method)
    rescue NameError
      # Method doesn't exist on this class
      nil
    end

    # Internal: Extract type from RBI files.
    def extract_from_rbi(klass, method_name)
      class_name = klass.name
      return nil unless class_name

      # Look up in RBI signature cache
      signature = find_rbi_signature(class_name, method_name.to_s)
      return nil unless signature

      # Parse the signature return type
      parse_rbi_return_type(signature)
    end

    # Internal: Find RBI signature for a class method.
    #
    # Returns String signature or nil
    def find_rbi_signature(class_name, method_name)
      # Check cache first
      cache_key = "#{class_name}##{method_name}"
      return rbi_signature_cache[cache_key] if rbi_signature_cache.key?(cache_key)

      # Search for RBI files containing this class
      signature = search_rbi_files_for_signature(class_name, method_name)

      # Cache result (even if nil, to avoid repeated searches)
      rbi_signature_cache[cache_key] = signature
      signature
    end

    # Internal: Search through RBI files to find a method signature.
    def search_rbi_files_for_signature(class_name, method_name)
      return nil unless rbi_path

      # Convert class name to possible file paths
      # e.g., "User" -> user.rbi, "Nested::User" -> nested/user.rbi
      possible_paths = rbi_file_paths_for_class(class_name)

      possible_paths.each do |rbi_file|
        next unless rbi_file.exist?

        signature = extract_signature_from_rbi_file(rbi_file, class_name, method_name)
        return signature if signature
      end

      nil
    end

    # Internal: Generate possible RBI file paths for a class.
    def rbi_file_paths_for_class(class_name)
      paths = []

      # Handle namespaced classes: Foo::Bar::Baz
      parts = class_name.split("::")

      # Try: sorbet/rbi/foo/bar/baz.rbi (nested structure)
      nested_path = rbi_path.join(*parts.map(&:underscore)).sub_ext(".rbi")
      paths << nested_path

      # Try: sorbet/rbi/foo_bar_baz.rbi (flat structure)
      flat_name = class_name.gsub("::", "_").underscore
      paths << rbi_path.join("#{flat_name}.rbi")

      # Try: sorbet/rbi/annotations/*.rbi (search all annotation files)
      if rbi_path.join("annotations").exist?
        paths += Dir[rbi_path.join("annotations", "*.rbi")].map { |p| Pathname.new(p) }
      end

      # Try: sorbet/rbi/gems/**/*.rbi (Tapioca gem RBIs)
      if rbi_path.join("gems").exist?
        paths += Dir[rbi_path.join("gems", "**", "*.rbi")].map { |p| Pathname.new(p) }
      end

      paths.uniq
    end

    # Internal: Extract a method signature from an RBI file.
    def extract_signature_from_rbi_file(rbi_file, class_name, method_name)
      content = File.read(rbi_file)

      # Simple regex-based extraction (works for most cases)
      # Pattern: sig { ... returns(Type) }
      #          def method_name

      # Match class/module definition
      class_pattern = /(?:class|module)\s+#{Regexp.escape(class_name)}\b/
      return nil unless content.match?(class_pattern)

      # Find the class body
      class_start = content.index(class_pattern)
      return nil unless class_start

      # Look for method definition within reasonable proximity
      method_pattern = /sig\s*\{[^}]*returns\(([^)]+)\)[^}]*\}\s*\n\s*def\s+#{Regexp.escape(method_name)}\b/m

      if (match = content[class_start..-1]&.match(method_pattern))
        return match[1] # Return the type from returns(...)
      end

      nil
    rescue StandardError
      # File read or parsing error - gracefully ignore
      nil
    end

    # Internal: Parse a return type string from RBI signature.
    #
    # type_string - String like "String", "T.nilable(Integer)", "T::Array[String]"
    #
    # Returns Hash with :typespec_type, :nilable, :array or nil
    def parse_rbi_return_type(type_string)
      return nil unless type_string

      type_string = type_string.strip
      result = {
        typespec_type: nil,
        nilable: false,
        array: false,
      }

      # Handle T.nilable wrapper
      if type_string.match?(/^T\.nilable\((.+)\)$/)
        result[:nilable] = true
        type_string = type_string.match(/^T\.nilable\((.+)\)$/)[1]
      end

      # Handle T::Array wrapper
      if type_string.match?(/^T::Array\[(.+)\]$/)
        result[:array] = true
        type_string = type_string.match(/^T::Array\[(.+)\]$/)[1]
      end

      # Map the core type
      result[:typespec_type] = map_rbi_type(type_string)

      result[:typespec_type] ? result : nil
    end

    # Internal: Map an RBI type string to TypeSpec type.
    def map_rbi_type(type_string)
      # Look up in config mapping
      mapped_type = TypeSpecFromSerializers.config.sorbet_to_typespec_type_mapping[type_string]
      return mapped_type if mapped_type

      # Handle T::Boolean
      return :boolean if type_string == "T::Boolean"

      # For custom classes, use the type string as-is
      type_string
    end

    # Internal: Cache for RBI signatures to avoid repeated file parsing.
    def rbi_signature_cache
      @rbi_signature_cache ||= {}
    end

    # Internal: Extract type information from a Method object.
    def extract_from_method(method)
      sig = T::Utils.signature_for_method(method)
      return nil unless sig&.return_type

      sorbet_type_to_typespec(sig.return_type)
    rescue StandardError
      # Sorbet introspection failed, fall back to other inference methods
      nil
    end

    # Internal: Convert a Sorbet type object to TypeSpec type information.
    #
    # sorbet_type - The Sorbet type object from the signature
    #
    # Returns Hash with :typespec_type, :nilable, :array keys
    # Returns nil if type cannot be mapped
    def sorbet_type_to_typespec(sorbet_type)
      result = {
        typespec_type: nil,
        nilable: false,
        array: false,
      }

      # Handle T.nilable wrapper
      if nilable?(sorbet_type)
        result[:nilable] = true
        sorbet_type = unwrap_nilable(sorbet_type)
      end

      # Handle T::Array wrapper
      if array_type?(sorbet_type)
        result[:array] = true
        sorbet_type = unwrap_array(sorbet_type)
      end

      # Map the core type
      result[:typespec_type] = map_sorbet_type(sorbet_type)

      result[:typespec_type] ? result : nil
    end

    # Internal: Check if a Sorbet type is nilable (T.nilable wrapper).
    def nilable?(sorbet_type)
      # Handle SimplePairUnion (T.nilable in runtime)
      if sorbet_type.class.name == "T::Private::Types::SimplePairUnion"
        return sorbet_type.instance_variable_get(:@raw_b) == NilClass ||
               sorbet_type.instance_variable_get(:@raw_a) == NilClass
      end

      return false unless sorbet_type.respond_to?(:raw_type)

      # T.nilable wraps types in a T::Types::Union with NilClass
      sorbet_type.is_a?(T::Types::Union) &&
        sorbet_type.types.any? { |t| t == T::Utils.coerce(NilClass) }
    end

    # Internal: Unwrap T.nilable to get the underlying type.
    def unwrap_nilable(sorbet_type)
      return sorbet_type unless nilable?(sorbet_type)

      # Handle SimplePairUnion
      if sorbet_type.class.name == "T::Private::Types::SimplePairUnion"
        raw_a = sorbet_type.instance_variable_get(:@raw_a)
        raw_b = sorbet_type.instance_variable_get(:@raw_b)
        return raw_a == NilClass ? raw_b : raw_a
      end

      # Find the non-nil type in the union
      sorbet_type.types.find { |t| t != T::Utils.coerce(NilClass) }
    end

    # Internal: Check if a Sorbet type is an array type.
    def array_type?(sorbet_type)
      sorbet_type.is_a?(T::Types::TypedArray)
    end

    # Internal: Unwrap T::Array to get the element type.
    def unwrap_array(sorbet_type)
      return sorbet_type unless array_type?(sorbet_type)

      sorbet_type.type
    end

    # Internal: Map a Sorbet type to a TypeSpec type.
    #
    # Returns Symbol for built-in types, String for custom types, or nil
    def map_sorbet_type(sorbet_type)
      # Get the raw type class if available
      type_class = if sorbet_type.respond_to?(:raw_type)
        sorbet_type.raw_type
      elsif sorbet_type.is_a?(Class)
        sorbet_type
      else
        # Unknown type structure
        return nil
      end

      # Get the class name
      type_name = type_class.is_a?(Class) ? type_class.name : type_class.to_s

      # Look up in config mapping
      mapped_type = TypeSpecFromSerializers.config.sorbet_to_typespec_type_mapping[type_name]
      return mapped_type if mapped_type

      # Handle T::Boolean specially (it's not a real class)
      return :boolean if type_name == "T::Boolean"

      # For custom classes, use the class name as-is
      # This will become a reference to a custom TypeSpec type
      type_name if type_class.is_a?(Class)
    end
    end
  end
end
