# frozen_string_literal: true

module TypeSpecFromSerializers
  # Public: Sorbet integration for type inference.
  #
  # This module provides optional integration with Sorbet's runtime type system
  # and RBI files. It can extract type information from:
  # 1. Runtime signatures (T::Utils.signature_for_method)
  # 2. RBI files generated by Tapioca (in sorbet/rbi/ directory)
  #
  # The module gracefully degrades when sorbet-runtime is not present, making
  # Sorbet integration completely optional with zero configuration required.
  module Sorbet
  module_function

    # Public: Check if Sorbet runtime is available.
    #
    # Returns true if sorbet-runtime gem is loaded and the necessary APIs
    # are available for type extraction.
    #
    # Returns Boolean
    def available?
      !!(defined?(T::Utils) && T::Utils.respond_to?(:signature_for_method))
    end

    # Public: Get the RBI directory path.
    #
    # Returns Pathname or nil if directory doesn't exist or can't be accessed
    def rbi_path
      return @rbi_path if defined?(@rbi_path)

      @rbi_path = begin
        TypeSpecFromSerializers.rbi_dir.then { |path| path if path.exist? && path.directory? }
      rescue
        nil
      end
    end

    # Public: Check if RBI files are available for parsing.
    #
    # Returns true if sorbet/rbi/ directory exists (typical Tapioca setup).
    #
    # Returns Boolean
    def rbi_available?
      !rbi_path.nil?
    end

    # Public: Extract type information for a method from its Sorbet signature.
    #
    # Tries multiple sources in order:
    # 1. Runtime reflection (T::Utils.signature_for_method)
    # 2. RBI files (if available)
    #
    # klass       - The Class containing the method
    # method_name - The Symbol or String name of the method
    #
    # Returns a Hash with keys:
    #   :typespec_type - Symbol or String representing the TypeSpec type
    #   :nilable       - Boolean indicating if type is optional
    #   :array         - Boolean indicating if type is an array
    # Returns nil if no signature found
    #
    # Examples
    #
    #   class MySerializer
    #     extend T::Sig
    #
    #     sig { returns(String) }
    #     def name
    #       "example"
    #     end
    #   end
    #
    #   extract_type_for(MySerializer, :name)
    #   # => { typespec_type: :string, nilable: false, array: false }
    #
    def extract_type_for(klass, method_name)
      # Try TypeDSL first (if available), then runtime reflection, then RBI files
      extract_from_type_dsl(klass, method_name) ||
        (available? ? extract_from_runtime(klass, method_name) : nil) ||
        (rbi_available? ? extract_from_rbi(klass, method_name) : nil)
    end

    class << self
    private

      # Internal: Extract type from TypeDSL declaration.
      def extract_from_type_dsl(klass, method_name)
        return nil unless klass.respond_to?(:type_for_method)

        type_annotation = klass.type_for_method(method_name)
        return nil unless type_annotation

        # Handle plain Ruby classes
        if type_annotation.is_a?(Class)
          type_name = type_annotation.name
          mapped_type = config_type_mapping[type_name]
          result = {
            typespec_type: mapped_type || type_name,
            nilable: false,
            array: false,
            type_class: type_annotation,
          }
          return result
        end

        # Handle Sorbet type annotations
        sorbet_type_to_typespec(type_annotation)
      rescue
        # Type extraction failed
        nil
      end

      # Internal: Get type mapping from config.
      def config_type_mapping
        TypeSpecFromSerializers.config.sorbet_to_typespec_type_mapping
      end

      # Internal: Extract type from runtime reflection.
      def extract_from_runtime(klass, method_name)
        method = klass.instance_method(method_name.to_sym)
        extract_from_method(method)
      rescue NameError
        # Method doesn't exist on this class
        nil
      end

      # Internal: Extract type from RBI files.
      def extract_from_rbi(klass, method_name)
        class_name = klass.name
        return nil unless class_name

        # Look up in unified RBI index
        signature = rbi_unified_index["#{class_name}##{method_name}"]
        return nil unless signature

        # Parse the signature return type
        parse_rbi_return_type(signature)
      end

      # Internal: Build a unified index from all RBI files.
      #
      # Returns Hash mapping "ClassName#method_name" => return_type_string
      def rbi_unified_index
        return @rbi_unified_index if defined?(@rbi_unified_index)

        @rbi_unified_index = {}
        return @rbi_unified_index unless rbi_path&.exist?

        # Find RBI files, excluding gems/ (third-party gems won't have serializer methods)
        # Only check annotations/ and dsl/ directories for performance
        rbi_files = [
          *Pathname.glob(rbi_path.join("annotations", "**", "*.rbi")),
          *Pathname.glob(rbi_path.join("dsl", "**", "*.rbi")),
        ]

        # Parse each file and merge into unified index
        rbi_files.each do |rbi_file|
          tree = parse_rbi_file_cached(rbi_file)
          next unless tree

          # Extract all method signatures from this file
          tree.index.each do |fqn, nodes|
            next unless fqn.include?("#") # Only instance methods

            nodes.each do |node|
              return_type = node&.sigs&.first&.return_type
              @rbi_unified_index[fqn] ||= return_type if return_type
            end
          end
        rescue
          # Ignore errors in individual files
          next
        end

        @rbi_unified_index
      end

      # Internal: Parse an RBI file and cache the result.
      #
      # Returns parsed RBI tree or nil if parsing fails
      def parse_rbi_file_cached(rbi_file)
        @rbi_tree_cache ||= {}
        @rbi_tree_cache[rbi_file.to_s] ||= ::RBI::Parser.parse_file(rbi_file)
      rescue
        # Cache the failure to avoid re-parsing
        @rbi_tree_cache[rbi_file.to_s] = nil
      end

      # Internal: Parse a return type from RBI signature using RBI type system.
      #
      # type_string - String like "String", "T.nilable(Integer)", "T::Array[String]"
      #
      # Returns Hash with :typespec_type, :nilable, :array or nil
      def parse_rbi_return_type(type_string)
        type_string&.strip&.then { |s| ::RBI::Type.parse_string(s) }&.then { |t| rbi_type_to_typespec(t) }
      rescue
        # Parsing failed - return nil
        nil
      end

      # Internal: Convert an RBI::Type to TypeSpec type information.
      #
      # rbi_type - RBI::Type object (Nilable, Generic, Simple, etc.)
      #
      # Returns Hash with :typespec_type, :nilable, :array or nil
      def rbi_type_to_typespec(rbi_type)
        result = {
          typespec_type: nil,
          nilable: false,
          array: false,
        }

        # Unwrap T.nilable
        if rbi_type.is_a?(::RBI::Type::Nilable)
          result[:nilable] = true
          rbi_type = rbi_type.type
        end

        # Unwrap T::Array
        if rbi_type.is_a?(::RBI::Type::Generic) &&
            rbi_type.name.in?(["::T::Array", "T::Array"])
          result[:array] = true
          rbi_type = rbi_type.params.first
        end

        # Extract the base type name
        type_name = case rbi_type
        when ::RBI::Type::Simple, ::RBI::Type::Generic
          rbi_type.name
        else
          rbi_type.to_s
        end

        # Map to TypeSpec type (remove leading :: if present)
        result[:typespec_type] = map_rbi_type(type_name.delete_prefix("::"))

        result[:typespec_type] ? result : nil
      end

      # Internal: Map an RBI type string to TypeSpec type.
      def map_rbi_type(type_string)
        TypeSpecFromSerializers.config.sorbet_to_typespec_type_mapping[type_string] ||
          ((type_string == "T::Boolean") ? :boolean : type_string)
      end

      # Internal: Extract type information from a Method object.
      def extract_from_method(method)
        sig = T::Utils.signature_for_method(method)
        return nil unless sig&.return_type

        sorbet_type_to_typespec(sig.return_type)
      rescue
        # Sorbet introspection failed, fall back to other inference methods
        nil
      end

      # Internal: Convert a Sorbet type object to TypeSpec type information.
      #
      # sorbet_type - The Sorbet type object from the signature
      #
      # Returns Hash with :typespec_type, :nilable, :array, :type_class keys
      # Returns nil if type cannot be mapped
      def sorbet_type_to_typespec(sorbet_type)
        result = {
          typespec_type: nil,
          nilable: false,
          array: false,
          type_class: nil,
        }

        # Handle T.nilable wrapper
        if nilable?(sorbet_type)
          result[:nilable] = true
          sorbet_type = unwrap_nilable(sorbet_type)
        end

        # Handle T::Array wrapper
        if sorbet_type.is_a?(T::Types::TypedArray)
          result[:array] = true
          sorbet_type = sorbet_type.type
        end

        # Extract the raw class if available
        result[:type_class] = extract_type_class(sorbet_type)

        # Map the core type
        result[:typespec_type] = map_sorbet_type(sorbet_type)

        result[:typespec_type] ? result : nil
      end

      # Internal: Extract the Ruby class from a Sorbet type object.
      #
      # sorbet_type - The Sorbet type object
      #
      # Returns Class or nil
      def extract_type_class(sorbet_type)
        # Handle SimplePairUnion
        if sorbet_type.instance_of?(::T::Private::Types::SimplePairUnion)
          raw_a, raw_b = sorbet_type.instance_variable_get(:@raw_a), sorbet_type.instance_variable_get(:@raw_b)
          type_class = (raw_a == NilClass) ? raw_b : raw_a
          return type_class if type_class.is_a?(Class)
        end

        # Handle TypedArray, Simple type, or class types
        return sorbet_type.type if sorbet_type.respond_to?(:type) && sorbet_type.type.is_a?(Class)
        return sorbet_type.raw_type if sorbet_type.respond_to?(:raw_type) && sorbet_type.raw_type.is_a?(Class)

        sorbet_type if sorbet_type.is_a?(Class)
      rescue
        # Type introspection failed - return nil
      end

      # Internal: Check if a Sorbet type is nilable (T.nilable wrapper).
      def nilable?(sorbet_type)
        # Handle SimplePairUnion (T.nilable in runtime)
        if sorbet_type.instance_of?(::T::Private::Types::SimplePairUnion)
          return sorbet_type.instance_variable_get(:@raw_b) == NilClass ||
              sorbet_type.instance_variable_get(:@raw_a) == NilClass
        end

        # T.nilable wraps types in a T::Types::Union with NilClass
        sorbet_type.respond_to?(:raw_type) &&
          sorbet_type.is_a?(T::Types::Union) &&
          sorbet_type.types.any? { |t| t == T::Utils.coerce(NilClass) }
      end

      # Internal: Unwrap T.nilable to get the underlying type.
      def unwrap_nilable(sorbet_type)
        return sorbet_type unless nilable?(sorbet_type)

        # Handle SimplePairUnion
        if sorbet_type.instance_of?(::T::Private::Types::SimplePairUnion)
          raw_a, raw_b = sorbet_type.instance_variable_get(:@raw_a), sorbet_type.instance_variable_get(:@raw_b)
          return (raw_a == NilClass) ? raw_b : raw_a
        end

        # Find the non-nil type in the union
        sorbet_type.types.find { |t| t != T::Utils.coerce(NilClass) }
      end

      # Internal: Map a Sorbet type to a TypeSpec type.
      #
      # Returns Symbol for built-in types, String for custom types, or nil
      def map_sorbet_type(sorbet_type)
        type_class = sorbet_type.respond_to?(:raw_type) ? sorbet_type.raw_type : sorbet_type
        return nil unless type_class.is_a?(Class) || sorbet_type.respond_to?(:raw_type)

        type_name = type_class.is_a?(Class) ? type_class.name : type_class.to_s

        TypeSpecFromSerializers.config.sorbet_to_typespec_type_mapping[type_name] ||
          ((type_name == "T::Boolean") ? :boolean : (type_name if type_class.is_a?(Class)))
      end
    end
  end
end
