name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.8.0

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22

      - run: pnpm install --frozen-lockfile

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Rubocop
        run: bin/rubocop

      - name: Clean Types
        run: pnpm clean

      - name: Run Migrations
        run: pnpm migrate

      - name: Generate Types
        run: pnpm gen

      - name: Type Check
        run: pnpm tsc

      - name: ESLint
        run: pnpm lint

  test:
    name: test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' || matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [
          "3.2",
          "3.3",
        ]
        gemfile: [
          "Gemfile-rails.7.1.x",
          "Gemfile-rails.7.2.x",
        ]
        experimental: [false]
        include:
          - ruby: "3.3"
            os: ubuntu-latest
            gemfile: Gemfile-rails-edge
            experimental: true
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Migrations
        run: cd playground/vanilla && bin/rails db:prepare

      - name: Ruby Specs
        run: bin/rspec
